module Vmstat
  class Memory
    attr_accessor pagesize: Integer
    attr_accessor wired: Integer
    attr_accessor active: Integer
    attr_accessor inactive: Integer
    attr_accessor free: Integer
    attr_accessor pageins: Integer
    attr_accessor pageouts: Integer
    
    def wired_bytes: -> Integer
    def active_bytes: -> Integer
    def inactive_bytes: -> Integer
    def free_bytes: -> Integer
    def total_bytes: -> Integer

    def initialize: (pagesize: Integer, wired: Integer, active: Integer, inactive: Integer, free: Integer, pageins: Integer, pageouts: Integer) -> void
                  | (Integer pagesize, Integer wired, Integer active, Integer inactive, Integer free, Integer pageins, Integer pageouts) -> void
  end
end
